server:
  port: 9091
  servlet:
    context-path: /v1/poli

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sidemuc
    platform: postgres
    username: postgres
    password: Juan1990
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true