server:
  port: 9091
  servlet:
    context-path: /v1/poli

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-4-111-46.compute-1.amazonaws.com
    platform: postgres
    username: zvsxhkmypothzg
    password: 3cb0dda4fcbd2d1bdf2b070228c97f997f0435bf979a8c7ce644bb7964debd9b
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true